server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.53.20.21:3306/reggie?useSSL=false
    username: root
    password: root
  redis:
    host: 10.53.20.21
    port: 6379
    password: root
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: 1ms
        max-idle: 4
        min-idle: 0
  cache:
    redis:
      time-to-live: 1800000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-value: isDeleted
      logic-delete-field: 1
      logic-not-delete-value: 0

reggie:
#  path: C:\Users\Tomcat\Desktop\reggie\reggie\src\main\resources\static\images\
#  path: /Users/zhiqiang.guo/IdeaProjects/reggie/src/main/resources/static/images/
  path: src/main/resources/static/images/