server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reggie?useSSL=false
    username: root
    password: root

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-value: isDeleted
      logic-delete-field: 1
      logic-not-delete-value: 0

reggie:
#  path: C:\Users\Tomcat\Desktop\reggie\reggie\src\main\resources\static\images\
#  path: /Users/zhiqiang.guo/IdeaProjects/reggie/src/main/resources/static/images/
  path: static/images/